name: 'Fetch Secrets from Postman'
description: 'Fetches secrets from a Postman mock server and sets them as outputs.'
inputs:
  postman-mock-url:
    description: 'The URL of the Postman mock server.'
    required: true
outputs:
  secret-one:
    description: 'The first secret.'
  secret-two:
    description: 'The second secret.'
runs:
  using: 'node16'
  main: 'index.js'
